### ISSUE TITLE
Schedule a new Backend Team meeting time

### ISSUE THREAD

**Issue by wbbarr** [GatechVIP/no-code#1]
All members of the backend team need to find a new time for the meeting to see if we can get a better time than Wednesday at 7 PM.  

@pongad , @sichinumi , @dustsnow

**Comment by wbbarr** [comment]
Poll posted:  http://whenisgood.net/2da8rpx

**Comment by wbbarr** [comment]
Looks like no time is the best for everyone.  I believe that W at 7 PM is still most likely our best time.

**Comment by wbbarr** [comment]
We have confirmed that everyone can make the Wednesday at 7 PM time, so that will be our weekly sync-up time.

**Comment by ghost** [comment]
Where do we meet today?

**Comment by wbbarr** [comment]
We're meeting in CULC 469.

**Comment by penghou620** [comment]
I just read the email about the meeting time. Do we meet today?

Peng Hou

On Feb 6, 2013, at 6:23 PM, William Barr III notifications@github.com
wrote:

We have confirmed that everyone can make the Wednesday at 7 PM time, so
that will be our weekly sync-up time.

—
Reply to this email directly or view it on
GitHubhttps://github.com/GatechVIP/no-code/issues/1#issuecomment-13211710.

**Comment by wbbarr** [comment]
Yes, we are meeting today.
