### ISSUE TITLE
Research an annotation tool

### ISSUE THREAD

**Issue by robertam3** [GatechVIP/no-code#14]
Find an annotation tool and summarize the following:
    \* Design aspects -- What elements of the interface are necessary, useful, or not useful?
    \* Learning aspects -- What about the tool helps or hurts the learning process?
    \* Feature List -- What are the core features of the tool?
            \* We will use this information to narrow down our core feature list at the next meeting

Below are some suggestions to start with, but feel free to find your own. Also, let everyone know in the comments which tool you are working on.

Google Docs
Word
Adobe Reader
Diigo
szoter
labelme

@rduan8, @crystallo, @qrobbins3, @ore92, @rcrl3

**Comment by ghost** [comment]
word

**Comment by quincyjrobbins** [comment]
adobe reader

**Comment by robertam3** [comment]
I'll look into Diigo.

**Comment by crystallo** [comment]
Crocodoc

**Comment by ghost** [comment]
MarkUp
