### ISSUE TITLE
Get Working Hilary Install & Document Steps 

### ISSUE THREAD

**Issue by penghou620** [GatechVIP/no-code#16]
@pongad @sichinumi @Webs961 

I'm not very familiar with github. If I do this a wrong, please remove this issue.
I just want to inform you that I updated the installation wiki page. And If you got any problem or question when you follow the steps there, you could leave a comment here. 
Also, I have done the VHD file. If anyone needs it, we can arrange a time to copy that to you.

**Comment by wbbarr** [comment]
Completed.
