### ISSUE TITLE
Create Ubuntu VM image for future use

### ISSUE THREAD

**Issue by wbbarr** [GatechVIP/no-code#17]
We could use a VM image to distribute to new team members in order to get them up and running faster, and especially in the event that the current team cannot get Hilary working on their own VMs/machines.  This should be able to be used by VMware Player (as it seems to be more performant than Virtualbox).  

Some documentation about how to get the VM up and running would be useful; this information should be put into the [wiki on the VIP site](http://vip.gatech.edu/wiki/index.php?title=Hilary_VM_Image&action=edit), as we'll need to put login passwords and such there for the VM.  

@khomotso, if we create this VM, would we have somewhere to store the files so people could get them?  We probably don't want to make that publicly available.  Dr. Abler might be able to help with that.

**Comment by penghou620** [comment]
Could you be specific about 'How to get the VM up and running"?

**Comment by wbbarr** [comment]
Basically, some instructions that can help you get started after you download the VHD files (i.e. "What do you do with the VHD files") kind of documentation.

**Comment by wbbarr** [comment]
Should be deprecated with new install script.  I will create a new task to test the script on a vanilla Ubuntu image.
