### ISSUE TITLE
Create a "start Hilary" shell script

### ISSUE THREAD

**Issue by wbbarr** [GatechVIP/no-code#19]
Given the large number of dependencies in Hilary, a shell script to start them all would be very useful (Redis, Nginx, Cassandra, ElasticSearch, etc).

**Comment by penghou620** [comment]
I have done this script. Where Should I put it? @Webs961

**Comment by wbbarr** [comment]
I would probably make this a gist and share the link.

**Comment by penghou620** [comment]
Since we don't have place to push the start Hilary script, I upload the  script in my repo. 
Here is the url: https://github.com/dustsnow/sakaiproject_related.git
If you guys find any bugs, please let me know.
@Webs961, @pongad , @sichinumi

**Comment by sichinumi** [comment]
As discussed in our Wednesday meeting, I'll test this and create an issue for it if one doesn't exist already.
