### ISSUE TITLE
Scenarios and Personas

### ISSUE THREAD

**Issue by ghost** [GatechVIP/no-code#20]
Create a list of possible uses of a collaboration/annotation type tool(s) and create a list of possible personas of people who might use this.

**Comment by ghost** [comment]
I'll take care of this (by friday).

**Comment by robertam3** [comment]
Scenarios are done. :) I made a page on the wiki called Scenarios and Personas.

**Comment by ghost** [comment]
I have expanded the scenarios section.

**Comment by vishwajac** [comment]
Put up a few scenarios as well!

**Comment by robertam3** [comment]
Thanks guys, I think we have enough scenarios. What we need to discuss now are personas.
