### ISSUE TITLE
Preliminary UI Design

### ISSUE THREAD

**Issue by robertam3** [GatechVIP/no-code#21]
Check out the Scenarios and Personas page on the wiki and design a series of user interface mock-ups for one of the scenarios described. We need to be able to see the sequence of steps a user would have to go through to complete the scenario. Focus on getting the user through the task rather than on individual features. 

Before you start, try to find a free (or at least free trial version) UI design tool like Balsamiq. If you find one that you like, share it in the comments below and also on the wiki. A pros/cons list would be useful. If you can't find a good tool, or if it takes too long to learn how to use, go ahead and use whatever method you want to create your designs (photoshop, powerpoint, HTML/CSS, paper, etc.) You can also use SakaiDocs or Google Docs as a backdrop for an essay if you want. 

@rduan8, @crystallo, @qrobbins3, @ore92, @vishwajac

**Comment by ghost** [comment]
Here is a great list of open source mockup alternatives (stack exchange)::
http://stackoverflow.com/questions/156937/balsamiq-mockups-alternative-for-building-wireframes 

PowerPoint/Photoshop/Paint works fine as well.

**Comment by vishwajac** [comment]
I didn't get a chance to create a solid prototype per say, but I do have a few ideas on paper that I'll share at the meeting (be warned these are very preliminary). 

I've used Mockup builder in the past and it's pretty good. Some other ones I've found are: 
- MockingBird
- MockFlow
- HotGloo
- Invision
- JustProto
- inPresso

**Comment by robertam3** [comment]
My UI professor recommended Balsamiq along with the following:
- Pencil [http://pencil.evolus.vn/Default.html]
- Caretta
- CogTool
- Visual Basic
- Denim
- Microsoft SketchFlow

I have a PDF from my class with more information about these, and prototyping in general if anyone is interested.
