### ISSUE TITLE
No easy way to share files.

### ISSUE THREAD

**Issue by ghost** [GatechVIP/no-code#22]
I have tried uploading files to github, but there isn't an easy drag and drop web interface to upload them to GitHub. 

So far, emailing everybody works for now, but it would be good to have a centralized place to store all our design docs.

I was wondering if I could setup a shared dropbox folder so we can share our design docs and research. We can also store larger files (videos), or html code. If nothing else, it would at least be a redundant copy of our work. 

If you guys agree, could you post your dropbox email in the comments below? (It would also be good to have a email list here).

If you guys don't agree, then we'll find some other way.

**Comment by ghost** [comment]
or we can figure this out during our meeting.

**Comment by robertam3** [comment]
It can actually be very easy to host files on github. And unlike dropbox, github is suitable for hosting code. We're going to need to use github for code eventually, so I think everyone should start getting used to it now. I have not used github for Windows, so maybe you can ask for some assistance on how to use that. Will has already made a video tutorial for getting started: http://vip.gatech.edu/wiki/index.php/Using_Github

**Comment by crystallo** [comment]
crystalloxdd@gmail.com

**Comment by robertam3** [comment]
rreusch.lewis@gmail.com

**Comment by ghost** [comment]
Ok, I made the shared folder. You should receive an email asking you to join the folder together. 
If you haven't put your dropbox email here, please do so as soon as possible.

**Comment by ghost** [comment]
oasonibare3@gatech.edu

**Comment by ghost** [comment]
Hmm, so far, only 3 people have put their emails down.
To entice the rest of you, I put a collection of very cute kitten videos in the dropbox folders.
All you have to do to get them is to put your dropbox email down below (or email me).

I'll figure out how to upload files using git soon.

**Comment by vishwajac** [comment]
Vishwajac@gmail.com

**Comment by ghost** [comment]
It seems everybody in the design team has linked their dropbox. 
For those who didn't send me their email, I will try and post a mediafire/rapidshare link to share future powerpoint designs. 
You can find them in the wiki
