### ISSUE TITLE
Test Hilary start script

### ISSUE THREAD

**Issue by wbbarr** [GatechVIP/no-code#25]
Test the new Hilary start script -- see https://github.com/GatechVIP/no-code/issues/19 for more information.

**Comment by penghou620** [comment]
Hey, Guys,
I'm sorry that I cannot go to the meeting tonight.  I will finish up the
 Hilary Start script tonight.
So sorry about that

Peng Hou

On Feb 20, 2013, at 4:38 PM, William Barr III notifications@github.com
wrote:

Test the new Hilary start script -- see
#19https://github.com/GatechVIP/no-code/issues/19for more
information.

—
Reply to this email directly or view it on
GitHubhttps://github.com/GatechVIP/no-code/issues/25.

**Comment by sichinumi** [comment]
Script is up on Peng's repo, cross-linked here: https://github.com/dustsnow/sakaiproject_related.git

Testing now.
