### ISSUE TITLE
Scenario 2 -- Merged prototype for user testing

### ISSUE THREAD

**Issue by robertam3** [GatechVIP/no-code#26]
I'll be working on combining the ideas we discussed at the meeting for Scenario 2 (teacher grading a student paper) into one prototype. Ore, Crystal and I have sketched out a combination on paper, which I will implement using Balsamiq.

@ore92 and @crystallo -- I will get the prototype to you tomorrow or Saturday, which you can look at over the weekend and suggest anything you think should be changed by Monday. Please also start thinking about how user testing should work. We'll need a diverse group of professors/TA's and a strategy to get as much feedback as we can within a week.

**Comment by wbbarr** [comment]
If you need professors/TAs to review this, I can have the 2316 TA group be one of your trial groups.  Just let me know what you need me to do.  1301 as well, probably.

**Comment by robertam3** [comment]
Cool, that would be great. :) I don't think we'll want a whole group of CS TA's since we need people from a variety of disciplines, but I'll keep you posted. I'll have more specifics on how many people we need on Tuesday. Thanks!

**Comment by robertam3** [comment]
Here's the link to the merged prototype: https://georgiatech.mybalsamiq.com/projects/oaeannotationtool/naked/Initial+Assignment+View?key=2c643c683a8429d059bf1d4b48cf4484a4a7a234

Read the comments on the first page to find out how to get started. Not every button is clickable, but you can expand/collapse the grading and annotation tools, and you can add a comment with a check mark.

Crystal and Ore: Let me know by Monday if you have any suggestions for things I should add/change.

**Comment by ghost** [comment]
What if a professor just wanted to leave comments on a students work and then return it without assigning a grade?  Finding the submit button(which is under the grading button) might be a challenge. Should we have a return assignment button that is always visible?

**Comment by robertam3** [comment]
For next week, interview one TA/Professor to get more information about the grading process and about our design.

People to talk to:
- Dave Lawrence
- TAs
  - CS UI design
  - Psychology Research Methods
  - Robots & Society
- Professors
  - English
  - Technical Communication
  - Communication & Culture

Questions to ask:
- How do you usually grade assignments? Electronically? On paper? etc. What is your general grading process.
- Do you use rubrics? How do you make them? How strictly do you adhere to them?
- How would you describe your feedback process? Do you annotate students' work? Do you comment throughout, at the end, or not at all? 
  Check out/experiment with mockup on Balsamiq
- What do you think about this design? Is it simple or complicated? Are there any features that you think are missing or not needed?
- Ask them to talk out loud as they click through the prototypes
- With every new screen: What do you notice? What are you trying to do?
