### ISSUE TITLE
Where is oae.data.me defined?

### ISSUE THREAD

**Issue by penghou620** [GatechVIP/no-code#29]
@stuartf 
I spootted totally three oae.data.me.profile.displayName errors. I was wondering why other modules are insistent on calling me.profile.  I think there should be a bug when this object get defined. Where is oae.data.me defined?

**Comment by stuartf** [comment]
Sorry I missed this, I've been really busy the last couple days, it comes from Hilary in node_modules/oae-principals/lib/rest.user.js I think the data from that was restructured recently and the UI needs to be patched.

**Comment by penghou620** [comment]
Thanks for the reply.
