### ISSUE TITLE
Interview TA about Grading Senario

### ISSUE THREAD

**Issue by robertam3** [GatechVIP/no-code#31]
Ask questions about grading process and our current mockup.

**Comment by ghost** [comment]
I asked those, I will include them as soon as I can straighten out her answers

**Comment by robertam3** [comment]
I interviewed the graduate TA for my Robotics & Society class. He grades essays, homework, and exams (which are short answer). 

Grading Process:
- Does not work from a rubric, but wishes he could make one easily so he can keep grading consistent.
- Usually looks at the question, figures out what an acceptable answer will look like, and grade all responses for that question. If students do not meet those expectations or if someone finds additional information that he did not consider, he reevaluates his expectations.

UI Mockup:
- Looks simple and easy to use
- Didn't immediately get that the comments section in the Grading tab is for general comments about the paper
- Suggests comments specifically for adding/deducting points, link to rubric so grade is automatically generated
- Editable rubric while grading
- Wants to make grammar corrections so the student can see what they did wrong
