### ISSUE TITLE
Prototype for User (Student) Testing

### ISSUE THREAD

**Issue by vishwajac** [GatechVIP/no-code#33]
To Do: 
- Final prototype for first rounds of user (student) testing needs to be made (Keep it simple) 
- Questions to ask students/ what to look for during the process? 
- Make sure to give them a task to do rather and get feedback about how they performed the task, what the difficulties were, and what they were able to do easily. 

Meeting Minutes:
- Chat? Eliminate or not completely?
- Add other files or not for sources? Just urls or upload files (dropbox- space limitiations? 
- Versioning- no. of minutes before next save? Typical autosave? 
- +/- button not intuitive? add/delete new users? 
- Merge the top/left tab to the middle
- Menu toolbar- word art? 
- Test and see if users need all these tools or if its just going to make it more confused? 
- Collapse columns both canvas and left hand side
- Make two designs very similar to each other- teaching activity included

**Comment by ghost** [comment]
see the powerpoint in the dropbox. You can show either the 3rd version, or the 4th version.
If you choose the unnarrated one, you'll have to advance slides manually

**Comment by ghost** [comment]
The 5th version has been updated implementing the suggested changes. 
It's in the dropbox, and I also emailed you.

Sorry, forgot to update this thread
