### ISSUE TITLE
Load/Store Data From/To Database

### ISSUE THREAD

**Issue by penghou620** [GatechVIP/no-code#35]
stuart:
We use helenus as a client to cassandra for data persistance. In Hilary we then write a dao.js to abstract that into an api, you can see an example at 

https://github.com/sakaiproject/Hilary/blob/master/node_modules/oae-content/lib/internal/dao.content.js

**Comment by wbbarr** [comment]
Closed as duplicate of https://github.com/GatechVIP/no-code/issues/34
