### ISSUE TITLE
User Testing (Student)- What to look for! 

### ISSUE THREAD

**Issue by vishwajac** [GatechVIP/no-code#38]
- Questions to ask students/ what to look for during the process? 
      -  We want to know how users interact with the system
      -  If its intuitive to the user where everything is- how to add other users, delete users, add/delete sources, get other version of the document, be able to identify who made change when. 
      - Type text into the middle and insert/delete comments 
      - Edit the text 
      - No other media for canvas apart from comments- eliminates need for scrolling canvas 
      - Sources- pop up window for inserted text 
- Make sure to give them a task to do rather and get feedback about how they performed the task, what the difficulties were, and what they were able to do easily.

**Comment by khomotso** [comment]
It will also be good to quantify success/difficulty users are having with particular aspects of the design, e.g.:
- 4 out of 5 users had no difficulty seeing how to revert to an earlier version
- 3 out of 5 users didn't see the button for adding users

**Comment by vishwajac** [comment]
Created a page under Wiki to enter your feedback from users. I got pretty good feedback from 3 users and will try and put it up there later today!

**Comment by vishwajac** [comment]
Continue user testing while working on the final (merged) prototype! Make sure to get feedback from at least 3 users for the next meeting.

**Comment by vishwajac** [comment]
Done with the merged prototype scenarios. List of tasks you could ask each user are in the "notes" section of the powerpoint!

**Comment by ghost** [comment]
Yeah, this is an old thread. The user testing for the 4th prototype has been done already. I went ahead and closed this.
