### ISSUE TITLE
Merged Prototype- User Testing (Annotation Scenario)

### ISSUE THREAD

**Issue by vishwajac** [GatechVIP/no-code#42]
- Focus on how information is presented on the screen independently
- Test static cases
- Does it make sense or does the user get totally lost? 
- Where they go first? 
- User needs to drive the testing

Tests: 
- 3 people 
- Update powerpoint to reflect static user testing case 
- Keep run-through to about 15 minutes 

Post Your Results Here:
https://github.com/GatechVIP/no-code/wiki/User-Testing:-Annotations-Scenario

**Comment by ghost** [comment]
I got this.

**Comment by ghost** [comment]
Ok, the results of my testing are on the wiki (also in dropbox)

**Comment by ghost** [comment]
Hmm, missed you guys. Well the general consensus from my user testing is that everything looks fine, but we could do away with a few unnecessary features (the colored text, colored mouse cursors), simplify the toolbar, and add a chat feature. I'm going to create the simplified prototype for the backend team meeting tomorrow. 

If any of you guys have done any user testing, add your results to the wiki. I don't think I have seen any work from you Quincy.

We are going to start creating the js prototype next week.
