### ISSUE TITLE
User Testing With Paper Prototype (Grading Scenario)

### ISSUE THREAD

**Issue by robertam3** [GatechVIP/no-code#43]
Guide 2 TAs/Professors through one prototype design on Balsamiq. I will post a complete walk-through of the interviewing process tomorrow (3/27). Familiarize yourself with the prototype so if the user gets stuck you now how to help them!

Document your results on the wiki.

@ore92, @crystallo

**Comment by robertam3** [comment]
I put some notes on the prototypes so you know what the goal is for each mockup screen. Here are the links to the actual prototypes:
Prototype 1: https://georgiatech.mybalsamiq.com/projects/annotationtoolprototype1/naked/Initial%20Assignment%20View?key=0607c4c98e6ac8aef3ec192745ac52f5a427c260
Prototype 2: https://georgiatech.mybalsamiq.com/projects/annotationtoolprototype2/naked/Initial%20Assignment%20View?key=26e8181b693fcf11c2e3485ad901a3aaf59b217c

Walk through them yourselves so you know what to expect during user testing.

**Comment by robertam3** [comment]
Here's a wiki page to put your observations from testing. https://github.com/GatechVIP/no-code/wiki/UI-Testing----Grading-Scenario 

I only have observations from one user so far, but I have another interview set up before the meeting today and should have more notes to share this afternoon.

**Comment by crystallo** [comment]
Here is one user testing result:
https://github.com/GatechVIP/no-code/wiki/User-Testing:-Grading-Scenario-2

Another user was not available on Friday and Monday. We are planning on doing the interview within these couple days.
