### ISSUE TITLE
Has the frontend-prototype created?

### ISSUE THREAD

**Issue by penghou620** [GatechVIP/no-code#44]
I know the frontend-prototype repo was created. 
But there's nothing in the repo. Where can I get the "fundamental" code to start with?

**Comment by sichinumi** [comment]
My bad, I got slammed this weekend with projects and completely forgot to copy the code over. For now, you can access the code at my repo: username is sichinumi, repo name is prototate, should be public.

I'll copy the code over as soon as I get to my computer - it might be best to wait to fork from there.

-----Original Message-----
From: dustsnow
Sent: 4/1/2013 12:12 PM
To: GatechVIP/no-code
Cc: Alvin Yan
Subject: [no-code] Has the frontend-prototype created? (#44)

I know the frontend-prototype repo was created. 
But there's nothing in the repo. Where can I get the "fundamental" code to start with?

**Comment by sichinumi** [comment]
The code has been populated across - feel free to fork from frontend-prototype now.
