### ISSUE TITLE
5 Question to as User- Final Testing on HTML Annotation Prototype

### ISSUE THREAD

**Issue by vishwajac** [GatechVIP/no-code#47]
- Keep in mind what the goals for our project are
- Keep the language simple 
- What are we looking for?

**Comment by ghost** [comment]
I've made a wiki page for this:
https://github.com/GatechVIP/no-code/wiki/User-Testing-Questions:-Annotations-Scenario

**Comment by khomotso** [comment]
There's a point I keep trying to make, probably badly, but it's this:
asking people for their opinion of a design is not really user testing,
it's market research. All the questions in this doc are asking people to
try to be designers themselves, and render their opinion from that
perspective, which is not the best way to learn about the strengths or
weaknesses of a given interaction design.

The wikipedia article on usability testing does a reasonable job of
summarizing this:

http://en.wikipedia.org/wiki/Usability_testing

**Comment by ghost** [comment]
Yes, I understand what you're trying to say, don't just ask them for their opinions, see how they react (I still think users should still give their overall opinion at the end of usability testing, as a sort of conclusion).

Right now It's kinda hard to do real user testing on a paper prototype. It's like asking people if they like a car based on a picture, not a test drive. 

The backend team has decided that the best use of developer time would be to concentrate on features that are shared by with both prototypes (annotation, highlighting, text editing, etc.), and then see if there is enough time to work on the annotation scenario. 

Nonetheless, I have updated the article to reflect what you have been trying to say.

**Comment by ghost** [comment]
I think we were a bit overly ambitious with our design. In the future, we should probably design with implementation in mind (just as an architect keeps into account the funds and resources he has available when designing a building).

**Comment by ghost** [comment]
oops, sorry, here is the new link:
https://github.com/GatechVIP/no-code/wiki/Usability-Testing-vs-Market-Research
