### ISSUE TITLE
Get a working Hilary install & Document Process.  

### ISSUE THREAD

**Issue by wbbarr** [GatechVIP/no-code#6]
By the end of the Week 4 milestone, everyone in the Backend team should have a working Hilary install and should write down the process and pitfalls in https://github.com/GatechVIP/Hilary/wiki/New-Hilary-Installation-Guide.

**Comment by wbbarr** [comment]
I'm currently trying to use the new nginx.conf file that is in @stuartf's repo, but I seem to be running into an error where Nginx states that the user block (line 1) is invalid.  I'll tinker with it some more tomorrow.

**Comment by penghou620** [comment]
@Webs961 
You might want to check what the user name of nginx is on your machine. 
run `more /etc/passwd` and find the name start with 'www'

**Comment by wbbarr** [comment]
New information:  You must have a 3akai-ux cloned from stuartf and be in the hilary-grunt branch (`git checkout hilary-grunt`), ideally somewhere near the Hilary folder.  

Then `sudo npm install -g grunt`

Then `sudo npm install -d` in the 3akai-ux directory (after you're on the hilary-grunt branch)

Then create a file called nginx.json.  That file should look like the following:

`{
    "NGINX_USER": "USERNAME",
    "NGINX_GROUP": "GROUP",
    "UX_HOME":  "PATH/TO/3akai-ux",
    "LOCAL_FILE_STORAGE_DIRECTORY": "/path/to/store/uploaded/files",
    "NGINX_HOSTNAME": "EXAMPLEHOST.COM"
}`

then run `grunt configNginx`

Copy the newly created file into the nginx config directory.  Reload the nginx config file.  

At this stage, I am able to connect to the endpoint, but I'm getting a load timeout for some of the modules, and the admin page does not render correctly at all (i.e. the page layout is mostly there, but none of the buttons, text, or anything like that is there).

**Comment by wbbarr** [comment]
Still no resolution to this.  I am sending an e-mail to the oae-dev list as soon as I can get back to my desktop to pin down the exact error message.

**Comment by stuartf** [comment]
there's actually some discussion going on about it on irc, it turns out there's a cyclic dependency in the js at this point that we're working to clean up

**Comment by wbbarr** [comment]
Completed.
